name: convert_json_model
description: Generate model class from Json file. partly inspired by json_model.
version: 0.0.1
author: Linus Nowomukama
homepage: https://github.com/linlak/convert_json_model

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^2.0.0
  expressions: ^0.2.0
  io: ^1.0.0
  json_annotation: ^4.0.0
  json_serializable: ^4.0.3
  logging: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.12.2
  build_runner_core: ^6.1.12
